### ISSUE TITLE
Very high CPU usage, cannot run 2 instances

### ISSUE THREAD

**Issue by chappjc** [decred/cgminer#20]
There may be two issues here, but the most apparent (and common in the forums) is that cgminer maxes out up to 2 CPU cores when GPU mining.  Official Catalyst drivers are up-to-date.  I can identify no cgminer switches or system environment variables that affect this issue.  Interestingly, note that if a single cgminer instance utilizes 2 GPUs, the CPU usage seems to be no higher than if 1 GPU is hashing.  I described the other issue, which is possibly related, in [this issue](https://github.com/decred/cgminer/issues/15#issuecomment-186859096).

The possibly-related issue distills to the following.  When running 2 instances for different GPUs, both miners slow down by more than half of hash rate they can achieve alone. This seems like it is related to the CPU issue, but it may be some resource competition or driver issue that prevents 2 processes from doing the same crazy behavior at the same time.  This makes it effectively impossible to utilize 2 GPUs in the same machine with cgminer; my dual-NVIDIA machine with ccminer has no such issues.

**Comment by jolan** [comment]
Should be fixed by #27.

**Comment by chappjc** [comment]
Unfortunately, not fixed.  On Windows amd64 it pegs 3 cores to 100%.  I'll check Linux.

```
me@host MINGW64 ~/builds/cgminer-decred-3.7
$ ./cgminer -V
cgminer 0.0.5-decred

```

**Comment by jolan** [comment]
Thanks for checking, looks like some of the unmerged parts from #29 would fix this.

**Comment by jolan** [comment]
Could use some more data from people experiencing this.

My own results thus far:

Arch Linux + i7-4790k + R9 Nano = 0% CPU utilization
Arch Linux + i7-4790k + 750ti+960 = 200% CPU utilization
Windows 7 64-bit + i3-4160 + 980ti = ~320% CPU utilization

**Comment by jcvernaleo** [comment]
Just to add to @jolan's data, my system (which is barely good enough for testnet mining but at least it is a data point):
Ubuntu Linux +  i7-4790K + i915 (or some sort of intel graphics) = 1.3% CPU (max, usually lower).

**Comment by chappjc** [comment]
To be a little more specific

Arch Linux + Intel Q6600 + R9 290x + R9 280x (latest Catalyst from repo) = lots of CPU, 200%+ probably, will get number in a few days
Windows 7 64-bit on above machine (dual boot) = lots of CPU, 300%+, haven't booted in a while
Windows 7 64-bit + dual xeon (16 logical core) + 980 + old quadro = >300%

Don't even try 2 cgminer instances on the first setup.

**Comment by jcvernaleo** [comment]
Closing since this repo is no longer maintained.
